sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov=src/

after_success:
  - coveralls

notifications:
  email: false
