sudo: false

language:
  - python

python:
  - 2.6
  - 3.0
  - 3.6

install:
    - pip install tox-travis
    - pip install coveralls

script:
 - tox

after_success:
  - coveralls

notifications:
  email: false
